// นิยามรายข้อของ "เกณฑ์เดิม" (highland 16 ข้อ / island 15 ข้อ) — ใช้ร่วมกันระหว่างสคริปต์วิเคราะห์
// ตรรกะคะแนนถอดจาก newhighland: app/Services/ScoreService.php และ IslandScoreService.php
// (ตรวจสอบแล้วกับเรคคอร์ดจริง highland sc_id=1063020130/2567 = 68.14 · island sc_id=1091560035/2568 = 71.38)

/** กลุ่มข้อมูลพื้นฐาน — ใช้จำแนกว่าข้อมูลแต่ละข้อ "มาจากไหน" และ "ใครเป็นเจ้าของข้อมูล" */
export const GROUPS = {
  geo: {
    key: "geo",
    label: "ภูมิศาสตร์ (วัดอัตโนมัติ)",
    source: "Google Maps Elevation/Directions API — ระบบคำนวณให้ ไม่ต้องกรอก",
    verifiable: "auto",
  },
  access: {
    key: "access",
    label: "การเข้าถึงและคมนาคม",
    source: "โรงเรียนกรอก + เขตรับรอง (ยังไม่มีชั้นข้อมูลกลาง)",
    verifiable: "declared",
  },
  admin: {
    key: "admin",
    label: "เขตปกครองและสถานะทางการ",
    source: "ทะเบียนราชการ (อปท./ชายแดน/ประกาศกระทรวงการคลัง) — ตรวจสอบย้อนได้",
    verifiable: "registry",
  },
  utility: {
    key: "utility",
    label: "สาธารณูปโภคพื้นฐาน",
    source: "โรงเรียนกรอก (น้ำ/ไฟ/โทรศัพท์/อินเทอร์เน็ต)",
    verifiable: "declared",
  },
  learner: {
    key: "learner",
    label: "ลักษณะผู้เรียน",
    source: "DMC/ทะเบียนนักเรียน + ระบบ ปัจจัยพื้นฐานนักเรียนยากจน (กสศ.)",
    verifiable: "registry",
  },
  structure: {
    key: "structure",
    label: "โครงสร้างสถานศึกษา",
    source: "ทะเบียนโรงเรียน (สาขา/ห้องเรียนสาขา)",
    verifiable: "registry",
  },
  screen: {
    key: "screen",
    label: "ด่านคัดกรอง (ไม่คิดคะแนน)",
    source: "โรงเรียนกรอก/เขตยืนยัน",
    verifiable: "declared",
  },
};

const opt = (map) => map;

/** ---------------- HIGHLAND — 16 ข้อ รวม 100 คะแนน ---------------- */
export const HIGHLAND_ITEMS = [
  {
    no: 1,
    key: "citeria01",
    scoreKey: "score01",
    title: "ระดับความสูงเหนือระดับน้ำทะเล ณ จุดสูงสุดของเส้นทางโรงเรียน–ศาลากลางจังหวัด",
    short: "ความสูงจุดสูงสุด",
    unit: "เมตร",
    kind: "numeric",
    max: 30,
    group: "geo",
    rule: "ถ้า ≥500 ม. หรือ ≥ ค่าเฉลี่ยความสูง → 15 + (min(ค่า,500) × 15/500) ; ไม่เข้าเงื่อนไข = 0",
    cap: 500,
    note: "ข้อเดียวกินคะแนน 30/100 — เป็นตัวกำหนดผลการคัดกรองมากที่สุด",
  },
  {
    no: 2,
    key: "citeria02",
    scoreKey: "score02",
    title: "เขตติดต่อระหว่างโรงเรียนกับพื้นที่ชายแดนประเทศเพื่อนบ้าน",
    short: "ชายแดน",
    kind: "single",
    max: 5,
    group: "admin",
    options: opt({
      1: { label: "หมู่บ้าน/เขตบริการติดชายแดน", points: 5 },
      2: { label: "ตำบลติดชายแดน", points: 4 },
      3: { label: "อำเภอติดชายแดน", points: 3 },
      4: { label: "จังหวัดติดชายแดน", points: 2 },
      5: { label: "ไม่อยู่ในจังหวัดติดชายแดน", points: 0 },
    }),
  },
  {
    no: 3,
    key: "citeria03",
    scoreKey: "score03",
    title: "เขตการปกครองส่วนท้องถิ่นที่โรงเรียนตั้งอยู่",
    short: "เขต อปท.",
    kind: "single",
    max: 5,
    group: "admin",
    options: opt({
      1: { label: "อบต.", points: 5 },
      2: { label: "เทศบาลตำบล", points: 4 },
      3: { label: "เทศบาลเมือง", points: 3 },
      4: { label: "เทศบาลนคร", points: 0 },
    }),
  },
  {
    no: 4,
    key: "citeria041",
    scoreKey: "score04",
    flagKey: "citeria04",
    title: "ระยะทางช่วงที่รถยนต์ขับเคลื่อนสองล้อไปไม่ได้ (บางฤดูกาล/ตลอดปี)",
    short: "ถนนรถ 2 ล้อไปไม่ได้",
    unit: "กิโลเมตร",
    kind: "numeric",
    max: 5,
    group: "access",
    rule: "min(ระยะทาง, 5) คะแนน (1 กม. = 1 คะแนน) ; ถ้าเลือก 'ไม่มี' ให้ระยะทาง = 0",
    cap: 5,
  },
  {
    no: 5,
    key: "citeria05",
    scoreKey: "score05",
    title: "ระยะทางรวมเส้นทางหลัก ศาลากลางจังหวัด–โรงเรียน",
    short: "ระยะทางถึงศาลากลาง",
    unit: "กิโลเมตร",
    kind: "numeric",
    max: 5,
    group: "geo",
    rule: "min(ระยะทาง, 80) × 5/80",
    cap: 80,
  },
  {
    no: 6,
    key: "citeria06",
    scoreKey: "score06",
    title: "ลักษณะการเดินทางด้วยระบบขนส่งสาธารณะ",
    short: "ขนส่งสาธารณะ",
    kind: "single",
    max: 5,
    group: "access",
    options: opt({
      1: { label: "ไม่มีรถประจำทาง", points: 5 },
      2: { label: "≤2 เที่ยว/วัน", points: 4 },
      3: { label: "≤4 เที่ยว/วัน", points: 3 },
      4: { label: "≤6 เที่ยว/วัน", points: 1 },
      5: { label: ">6 เที่ยว/วัน", points: 1 },
    }),
  },
  {
    no: 7,
    key: "citeria07",
    scoreKey: "score07",
    title: "แหล่งน้ำหลักสำหรับอุปโภค-บริโภคในโรงเรียน",
    short: "แหล่งน้ำ",
    kind: "multi",
    max: 6,
    group: "utility",
    rule: "ใช้ค่า id สูงสุดที่เลือก",
    options: opt({
      1: { label: "ต่อจากแหล่งน้ำธรรมชาติ (ประปาภูเขา/ลำธาร)", points: 6 },
      2: { label: "สูบจากบ่อ/สระ/บาดาลของชุมชน", points: 5 },
      3: { label: "สูบจากบ่อ/สระ/บาดาลของโรงเรียน", points: 4 },
      4: { label: "ประปาหมู่บ้าน/ชุมชน", points: 3 },
      5: { label: "ประปา อปท.", points: 2 },
      6: { label: "ประปาส่วนภูมิภาค", points: 1 },
    }),
  },
  {
    no: 8,
    key: "citeria08",
    scoreKey: "score08",
    title: "ระบบไฟฟ้า",
    short: "ไฟฟ้า",
    kind: "multi",
    max: 3,
    group: "utility",
    rule: "ใช้ค่า id สูงสุดที่เลือก",
    options: opt({
      1: { label: "พลังงานทางเลือก (โซลาร์/ลม/น้ำ/เครื่องปั่นไฟ)", points: 3 },
      2: { label: "ไฟฟ้าส่วนภูมิภาค", points: 0 },
    }),
  },
  {
    no: 9,
    key: "citeria09",
    scoreKey: "score09",
    title: "ระบบโทรศัพท์ที่ใช้ในโรงเรียน",
    short: "โทรศัพท์",
    kind: "multi",
    max: 3,
    group: "utility",
    rule: "ใช้ค่า id สูงสุดที่เลือก",
    options: opt({
      1: { label: "ไม่มีเครือข่ายสัญญาณ", points: 3 },
      2: { label: "ผ่านจานดาวเทียม", points: 2 },
      3: { label: "โทรศัพท์เคลื่อนที่", points: 1 },
      4: { label: "โทรศัพท์พื้นฐาน", points: 0 },
    }),
  },
  {
    no: 10,
    key: "citeria10",
    scoreKey: "score10",
    title: "ระบบอินเทอร์เน็ตที่ใช้ในโรงเรียน",
    short: "อินเทอร์เน็ต",
    kind: "multi",
    max: 3,
    group: "utility",
    rule: "ใช้ค่า id สูงสุดที่เลือก",
    options: opt({
      1: { label: "ไม่มีเครือข่าย Internet", points: 3 },
      2: { label: "จานรับสัญญาณดาวเทียม", points: 2 },
      3: { label: "ไร้สาย (มือถือ)", points: 1 },
      4: { label: "Leased line / Fiber", points: 0 },
    }),
  },
  {
    no: 11,
    key: "citeria11",
    scoreKey: "score11",
    title: "ร้อยละของนักเรียนกลุ่มชาติพันธุ์",
    short: "% ชาติพันธุ์",
    unit: "ร้อยละ",
    kind: "numeric",
    max: 5,
    group: "learner",
    rule: "ร้อยละ (เพดาน 100) × 5/100 — คำนวณจากตาราง highland_eval_hilltrib",
    cap: 100,
  },
  {
    no: 12,
    key: "citeria12",
    scoreKey: "score12",
    title: "จำนวนกลุ่มชาติพันธุ์ของนักเรียน",
    short: "จำนวนกลุ่มชาติพันธุ์",
    unit: "กลุ่ม",
    kind: "numeric",
    max: 5,
    group: "learner",
    rule: "min(จำนวนกลุ่ม, 5) — 1 กลุ่ม = 1 คะแนน",
    cap: 5,
  },
  {
    no: 13,
    key: "citeria13",
    scoreKey: "score13",
    title: "จำนวนนักเรียนยากจน/ยากจนพิเศษแบบมีเงื่อนไข",
    short: "นักเรียนยากจน",
    unit: "คน",
    kind: "numeric",
    max: 5,
    group: "learner",
    rule: "ร้อยละของนักเรียนทั้งหมด (เพดาน 50%) × 5/50",
    cap: null,
  },
  {
    no: 14,
    key: "citeria14",
    scoreKey: "score14",
    title: "จำนวนนักเรียนพักนอน",
    short: "นักเรียนพักนอน",
    unit: "คน",
    kind: "numeric",
    max: 5,
    group: "learner",
    rule: "min(จำนวน, 50) × 5/50",
    cap: 50,
  },
  {
    no: 15,
    key: "citeria15",
    scoreKey: "score15",
    title: "จำนวนโรงเรียนสาขา / ห้องเรียนสาขา",
    short: "สาขา",
    unit: "แห่ง",
    kind: "numeric",
    max: 5,
    group: "structure",
    rule: "1 สาขา = 3 · 2 สาขา = 4 · ≥3 สาขา = 5 · ไม่มี = 0",
    cap: 3,
  },
  {
    no: 16,
    key: "citeria16",
    scoreKey: "score16",
    title: "เป็นโรงเรียนพื้นที่พิเศษตามประกาศกระทรวงการคลัง",
    short: "ประกาศคลัง",
    kind: "single",
    max: 5,
    group: "admin",
    options: opt({
      1: { label: "ใช่", points: 5 },
      2: { label: "ไม่ใช่", points: 0 },
    }),
  },
];

/** ---------------- ISLAND — 15 ข้อ รวม 100 คะแนน (ข้อ 1 เป็นด่านคัดกรอง) ---------------- */
export const ISLAND_ITEMS = [
  {
    no: 1,
    key: "citeria01",
    scoreKey: "score01",
    title: "เป็นโรงเรียนพื้นที่เกาะ",
    short: "เป็นเกาะ",
    kind: "single",
    max: 0,
    group: "screen",
    options: opt({ 1: { label: "ใช่", points: 0 }, 2: { label: "ไม่ใช่", points: 0 } }),
  },
  {
    no: 2,
    key: "citeria02",
    scoreKey: "score02",
    title: "เขตการปกครองส่วนท้องถิ่นที่โรงเรียนตั้งอยู่",
    short: "เขต อปท.",
    kind: "single",
    max: 10,
    group: "admin",
    options: opt({
      1: { label: "อบต.", points: 10 },
      2: { label: "เทศบาลตำบล", points: 8 },
      3: { label: "เทศบาลเมือง", points: 6 },
      4: { label: "เทศบาลนคร", points: 4 },
    }),
  },
  {
    no: 3,
    key: "citeria03",
    scoreKey: "score03",
    title: "ลักษณะที่ตั้ง (มีสะพานเชื่อมแผ่นดินใหญ่หรือไม่)",
    short: "ลักษณะที่ตั้ง",
    kind: "single",
    max: 16,
    group: "geo",
    options: opt({
      1: { label: "ไม่มีสะพาน — ไปได้ทางเรือเท่านั้น", points: 16 },
      2: { label: "มีสะพาน / ไปได้ทั้งทางบกและน้ำ", points: 0 },
    }),
  },
  {
    no: 4,
    key: "citeria04",
    scoreKey: "score04",
    title: "พาหนะหลักในการเดินทาง",
    short: "พาหนะหลัก",
    kind: "single",
    max: 20,
    group: "access",
    options: opt({
      1: { label: "เรือไม่ประจำทาง", points: 20 },
      2: { label: "เรือประจำทาง ไม่ตลอดปี", points: 15 },
      3: { label: "เรือประจำทาง ตลอดปี", points: 10 },
      4: { label: "เรือเฟอร์รี่/แพขนานยนต์", points: 5 },
      5: { label: "ใช้รถเป็นหลัก", points: 0 },
    }),
  },
  {
    no: 5,
    key: "citeria05",
    scoreKey: "score05",
    title: "ระยะทางช่วงทางบก",
    short: "ระยะทางบก",
    unit: "กิโลเมตร",
    kind: "numeric",
    max: 5,
    group: "access",
    rule: "min(กม., 20) × 5/20",
    cap: 20,
  },
  {
    no: 6,
    key: "citeria06",
    scoreKey: "score06",
    title: "ระยะทางช่วงทางน้ำ",
    short: "ระยะทางน้ำ",
    unit: "กิโลเมตร",
    kind: "numeric",
    max: 5,
    group: "access",
    rule: "min(กม., 20) × 5/20",
    cap: 20,
  },
  {
    no: 7,
    key: "citeria07",
    scoreKey: "score07",
    title: "เวลาที่ใช้เดินทาง",
    short: "เวลาเดินทาง",
    unit: "นาที",
    kind: "numeric",
    max: 5,
    group: "access",
    rule: "min(นาที, 60) × 5/60",
    cap: 60,
  },
  {
    no: 8,
    key: "citeria08",
    scoreKey: "score08",
    title: "ค่าโดยสารต่อเที่ยว",
    short: "ค่าโดยสาร",
    unit: "บาท",
    kind: "numeric",
    max: 5,
    group: "access",
    rule: "min(บาท, 500) × 5/500",
    cap: 500,
  },
  {
    no: 9,
    key: "citeria09",
    scoreKey: "score09",
    title: "การเดินทางต่อหลังขึ้นฝั่ง",
    short: "เดินทางต่อ",
    kind: "single",
    max: 5,
    group: "access",
    options: opt({
      1: { label: "ทางเรือแล้วต่อด้วยเดินเท้า", points: 5 },
      2: { label: "เดินเท้าเท่านั้น", points: 4 },
      3: { label: "รถบนทางลำลอง/ทางเท้า", points: 3 },
      4: { label: "รถบนทางลาดยาง/คอนกรีต", points: 2 },
      5: { label: "ไม่ต้องเดินทางต่อ", points: 1 },
    }),
  },
  {
    no: 10,
    key: "citeria10",
    scoreKey: "score10",
    title: "ระบบไฟฟ้า",
    short: "ไฟฟ้า",
    kind: "single",
    max: 5,
    group: "utility",
    options: opt({
      1: { label: "พลังงานทางเลือกเท่านั้น", points: 5 },
      2: { label: "ไฟฟ้าส่วนภูมิภาค", points: 0 },
    }),
  },
  {
    no: 11,
    key: "citeria11",
    scoreKey: "score11",
    title: "แหล่งน้ำหลัก",
    short: "แหล่งน้ำ",
    kind: "single",
    max: 10,
    group: "utility",
    options: opt({
      1: { label: "แหล่งน้ำธรรมชาติ", points: 10 },
      2: { label: "บ่อ/สระ/บาดาลของชุมชน", points: 8 },
      3: { label: "บ่อ/สระ/บาดาลของโรงเรียน", points: 6 },
      4: { label: "ประปาหมู่บ้าน/ชุมชน", points: 4 },
      5: { label: "ประปา อปท.", points: 2 },
      6: { label: "ประปาส่วนภูมิภาค", points: 0 },
    }),
  },
  {
    no: 12,
    key: "citeria12",
    scoreKey: "score12",
    title: "ระบบอินเทอร์เน็ต",
    short: "อินเทอร์เน็ต",
    kind: "single",
    max: 5,
    group: "utility",
    options: opt({
      1: { label: "ไม่มีเครือข่าย", points: 5 },
      2: { label: "จานดาวเทียม", points: 4 },
      3: { label: "ไร้สาย (มือถือ)", points: 3 },
      4: { label: "Leased line / Fiber", points: 2 },
    }),
  },
  {
    no: 13,
    key: "citeria13",
    scoreKey: "score13",
    title: "ระบบโทรศัพท์",
    short: "โทรศัพท์",
    kind: "single",
    max: 5,
    group: "utility",
    options: opt({
      1: { label: "ไม่มีเครือข่าย", points: 5 },
      2: { label: "จานดาวเทียม", points: 4 },
      3: { label: "โทรศัพท์เคลื่อนที่", points: 3 },
      4: { label: "โทรศัพท์พื้นฐาน", points: 2 },
    }),
  },
  {
    no: 14,
    key: "citeria14",
    scoreKey: "score14",
    title: "เป็นพื้นที่พิเศษตามประกาศกระทรวงการคลัง",
    short: "ประกาศคลัง",
    kind: "single",
    max: 2,
    group: "admin",
    options: opt({ 1: { label: "ใช่", points: 2 }, 2: { label: "ไม่ใช่", points: 0 } }),
  },
  {
    no: 15,
    key: "citeria15",
    scoreKey: "score15",
    title: "จำนวนนักเรียนยากจน",
    short: "นักเรียนยากจน",
    unit: "คน",
    kind: "numeric",
    max: 2,
    group: "learner",
    rule: "ร้อยละของนักเรียนทั้งหมด (เพดาน 50%) × 2/50",
    cap: null,
  },
];

/** ระดับผลการคัดกรองของเกณฑ์เดิม */
export const LEVELS = [
  { key: 3, label: "กลุ่มที่ 3 ยุ่งยากมากที่สุด", min: 70 },
  { key: 2, label: "กลุ่มที่ 2 ยุ่งยากมาก", min: 60 },
  { key: 1, label: "กลุ่มที่ 1 ยุ่งยาก", min: 50 },
  { key: 0, label: "ไม่เข้ากลุ่ม", min: 0 },
];

export function levelOf(score) {
  for (const l of LEVELS) if (score >= l.min) return l;
  return LEVELS[LEVELS.length - 1];
}
